swagger: "2.0"
info:
  description: "spotify-service"
  version: "1.0.0"
  title: "Spotify"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "track"
  description: "Operaciones sobre track"
schemes:
- "https"
- "http"
paths:
  /artist:
    post:
      tags:
      - "Artist"
      summary: "crea un nuevo artista"
      description: "crea un nuevo artista"
      operationId: "nuevoArtista"
      parameters:
      - in: "body"
        name: "ArtistRequest"
        description: "objeto Artist"
        required: true
        schema:
          $ref: "#/definitions/ArtistRequest"
      responses:
        "200":
          description: "Created"
          schema:
            $ref: "#/definitions/ArtistResponse"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
            
definitions:
  TrackRequest:
    type: "object"
    required:
    - "name"
    - "genre"
    - "image"
    - "idArtist"
    properties:
      name:
        type: "string"
        
      image:
        type: "string"
        
      genre:
        type: "string"
        
      idArtist:
        type: "number"
     
        
  TrackResponse:
    type: "object"
    properties:
      idArtist:
        type: "number"
      name:
        type: "string"
      
      genre:
        type: "string"
        
      image:
        type: "string"
        
   
  ErrorNotFoundResponse:
    type: "object"
    properties:
      code:
        type: "string"
        example: "GENERIC_NOT_FOUND"
      message:
        type: "string"
        example: "Resource Not Found"
      result:
        type: "string"
        example: "GENERIC_NOT_FOUND"
  ErrorBadRequestResponse:
    type: "object"
    properties:
      code:
        type: "string"
        example: "GENERIC_BAD_REQUEST"
      message:
        type: "string"
        example: "Invalid Request"
      result:
        type: "string"
        example: "GENERIC_NOT_FOUND"
  ErrorInternalServerResponse:
    type: "object"
    properties:
      code:
        type: "string"
        example: "GENERIC_INTERNAL_SERVER_ERROR"
      message:
        type: "string"
        example: "Internal Server Error"
      result:
        type: "string"
        example: "GENERIC_INTERNAL_SERVER_ERROR"